local SentinelUI = loadstring(game:HttpGet("https://raw.githubusercontent.com/Vvoidddd/Sentinel-Hub/main/Release/UI/SentinelUI.lua"))()
local UI = SentinelUI.CreateWindow(Enum.KeyCode.RightShift)

local terminal = UI:CreateTab("Terminal")
terminal:Label("Welcome to Sentinel UI Terminal!")
terminal:Button("Print Hello", function()
    print("Hello from Sentinel UI!")
end)
terminal:Toggle("Auto Mode", false, function(state)
    print("Auto Mode:", state)
end)

local settings = UI:CreateTab("Settings")
settings:Label("Settings Panel")
settings:Button("Close UI", function()
    UI:Destroy()
end)
